import Head from "next/head"
import Link from "next/link"

export default function Avator() {
  return (
    <>
      <Head>
        <title>Create Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="backgroudiamge--avator--upload h-[100vh]">
        <div className="hidden w-full h-[100vh] md:block">
          {/* <img className="" src="Images/image 1  (2).svg" /> */}

          <div className="border-none z-20">
            <img className="h-[60%]  border-none  presbackmg--avator--upload  fixed !bottom-0 min-w-[100%] " />
          </div>
        </div>
        <div className=" hidden w-[100%] absolute top-[40px] md:flex md:justify-center  md:items-center mx-auto gap-4">
          <img src="Images/MaskGroup57 1 (1).svg" />
          <h4 className="Title--text md:text-[black]">ontheMoons</h4>
        </div>
        <div className="w-[100%]">
          <div className="flex items-center justify-center">
            <img
              className="hidden absolute top-[13%] md:block"
              src="Images/Group 67 (1).svg"
            />
          </div>
          <div className="relative  flex">
            <img className=" h-[100vh]" src="Images/Group 57.svg" alt="" />
            <img
              className="absolute w-[40%] flex items-center justify-center  xl:hidden right-24 bottom-0"
              src="Images/Group 67.svg"
              alt=""
            />
          </div>
          <div className="absolute xl:w-[80%] md:z-20 md:bottom-0 md:w-[100%] md:px-0 w-[50%] px-12 top-0">
            <div className="pt-[160px] md:w-[100%] md:px-9 md:absolute md:bottom-[20px] md:flex md:flex-col ">
              <div className="flex md:hidden items-center gap-4">
                <img src="Images/MaskGroup57 1.svg" />
                <h4 className="Title--text">ontheMoons</h4>
              </div>
              <h4 className="Subtitle--text md:flex md:h-[45px]   md:text-[36px] md:w-[100%] md:leading-3 w-[80%] md:pt-2 pt-6">
                Picture Upload
              </h4>
              <p className="paragraph--text  md:text-[16px] md:pt-2 md:leading-[24px]  pt-6 w-[88%] md:w-[80%] md:items-start md:text-start">
                Note* : Real Picture Upload (Minimum 1 mandatory)
              </p>

              <div className="flex items-center md:w-[90%] md:pt-2 pt-5 w-[77%]">
                <img
                  className="md:w-[183px] md:h-[146px] "
                  src="Images/Rectangle 18 (1).svg"
                  alt=""
                />
                <img
                  className="md:w-[183px] md:h-[146px] "
                  src="Images/Rectangle 19 (2).svg"
                  alt=""
                />
                <div className="bg-white cursor-pointer md:w-[75px] w-[65px] h-[63px] flex items-center justify-center rounded-[14px] baxshadow">
                  <svg
                    width="46"
                    height="47"
                    viewBox="0 0 46 47"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M11.5 23.688H34.5"
                      stroke="black"
                      stroke-width="3"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M23 35.188L23 12.188"
                      stroke="black"
                      stroke-width="3"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </div>

              <Link href="/userinformation">
                <div className="bg-white justify-center md:h-[60px] mt-8 flex items-center md:w-[100%] w-[77%] cursor-pointer rounded-[20px] h-[74px] md:rounded-[10px] md:mt-6 border-2 gap-5 border-white">
                  <h4 className="Button--text">Next</h4>
                  <img className="md:w-[14%]" src="Images/image 8 (1).svg" />
                </div>
              </Link>

              <div className="md:flex md:items-center md:justify-center md:flex-col">
                <div className="flex items-center  pr-[130px] md:pr-0 pt-8 justify-center">
                  <svg
                    width="120"
                    height="14"
                    viewBox="0 0 120 14"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <ellipse
                      cx="6.80554"
                      cy="6.72412"
                      rx="6.54236"
                      ry="6.5"
                      fill="white"
                    />
                    <ellipse
                      cx="33.4955"
                      cy="6.72412"
                      rx="6.54236"
                      ry="6.5"
                      fill="white"
                    />
                    <ellipse
                      cx="60.1859"
                      cy="6.72412"
                      rx="6.54236"
                      ry="6.5"
                      fill="white"
                    />
                    <ellipse
                      cx="86.8763"
                      cy="6.72412"
                      rx="6.54236"
                      ry="6.5"
                      fill="white"
                    />
                    <ellipse
                      cx="113.392"
                      cy="6.72412"
                      rx="6.54236"
                      ry="6.5"
                      fill="#AAAAAA"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
