import Head from "next/head"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="HomePage--background--Image h-[100vh]">
        <div className="flex items-center md:pt-9 justify-center">
          <svg
            className="md:w-[85%]"
            width="438"
            height="70"
            viewBox="0 0 438 70"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <g filter="url(#filter0_b_627_1422)">
              <path
                d="M0.0703125 -5.875H437.931L407.931 69.8047H30.0703L0.0703125 -5.875Z"
                fill="white"
                fill-opacity="0.22"
              />
              <path
                d="M30.7496 68.8047L1.54242 -4.875H436.459L407.251 68.8047H30.7496Z"
                stroke="white"
                stroke-width="2"
              />
            </g>
            <defs>
              <filter
                id="filter0_b_627_1422"
                x="-7.92969"
                y="-13.875"
                width="453.859"
                height="91.6797"
                filterUnits="userSpaceOnUse"
                color-interpolation-filters="sRGB"
              >
                <feFlood flood-opacity="0" result="BackgroundImageFix" />
                <feGaussianBlur in="BackgroundImageFix" stdDeviation="4" />
                <feComposite
                  in2="SourceAlpha"
                  operator="in"
                  result="effect1_backgroundBlur_627_1422"
                />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="effect1_backgroundBlur_627_1422"
                  result="shape"
                />
              </filter>
            </defs>
          </svg>
          <h4 className="absolute top-0 md:text-[18px] pt-3 md:pt-12 HomePage--title--text">
            Jhone Doe@7777
          </h4>
          <div className=" md:top-[240px] center-div">
            <img src="Images/Group 125.svg" alt="" />
          </div>
          <div className="md:absolute md:left-0 md:right-0 md:w-[100%] md:h-[300px] md:bottom-0">
            <Link href="/avator">
              <div
                onClick={() => console.log("you clicked Avator")}
                className="absolute  md:top-0 md:left-[60px] top-5 left-5"
              >
                <div className="">
                  <img
                    className="md:w-[80%] md:pt-[80px] md:px-0 "
                    src="Images/Frame (4).svg"
                    alt=""
                  />
                  <h5 className="absolute w-[100%] md:pl-[35px] pl-9 homepage-text md:top-11 md:z-40 centered top-[0] md:text-[23px] right-0">
                    <img
                      className="md:w-[10%]"
                      src="Images/image 20.svg"
                      alt=""
                    />
                    Change Avator
                  </h5>
                </div>
              </div>
            </Link>
            <Link href="/userinformation">
              <div
                onClick={() => console.log("you clicked Profile")}
                className="absolute md:top-0 md:right-0 md:left-[60px] top-5 right-5"
              >
                <div className="h-[900px] bg-transparent">
                  <img
                    className="md:w-[80%] md:pt-[10px]  md:px-0"
                    src="Images/Frame (4).svg"
                    alt=""
                  />
                  <h5 className="absolute w-[100%] md:pl-[45px] pl-12 homepage-text md:!top-[113px] md:z-40 centered !top-11 md:text-[23px] right-0">
                    <img
                      className="md:w-[13%]"
                      src="Images/Group 111.svg"
                      alt=""
                    />
                    My Profile
                  </h5>
                </div>
              </div>
            </Link>
            <div
              onClick={() => console.log("you clicked Area")}
              className="absolute cursor-pointer md:left-[60px] bottom-5 left-5"
            >
              <img
                className="md:w-[80%] md:pb-[68px]  md:px-0"
                src="Images/Frame (4).svg"
                alt=""
              />
              <h5 className="absolute w-[100%] md:pl-[30px] pl-12 homepage-text md:!top-[32px] md:z-40 centered !top-11 md:text-[23px] right-0">
                Enter Public Area
              </h5>
            </div>
            <div
              onClick={() => console.log("you clicked Metaverse")}
              className="absolute cursor-pointer md:left-[60px] md:right-0 bottom-5 right-5"
            >
              <img
                className="md:w-[80%] md:pt-24 md:px-0"
                src="Images/Frame (4).svg"
                alt=""
              />
              <h5 className="absolute w-[100%] md:pl-[20px] pl-12 homepage-text md:!top-[129px] md:z-40 centered !top-11 md:text-[23px] right-0">
                Enter My Metaverse
              </h5>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
